name: Build and Publish YAGSL vendordep
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version number"
        type: string
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      releaseVersion: ${{ inputs.releaseVersion }}
      working-directory: ./vendordep
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Change gradleRIO executable
        run: chmod a+x gradlew
        working-directory: ${{env.working-directory}}
      - name: Install roboRio toolchain
        run: ./gradlew installRoboRioToolchain
        working-directory: ${{env.working-directory}}
      - name: Build vendordep
        run: ./gradlew build
        working-directory: ${{env.working-directory}}
      - name: Publish vendordep
        run: ./gradlew publish
        working-directory: ${{env.working-directory}}
      - name: Update repository
        run: |
          git config --global user.name "thenetworkgrinch"
          git config --global user.email "thenetworkgrinch@users.noreply.github.com"
          git add .
          git commit -m "Upgrading to ${{ inputs.releaseVersion }}"
          git push
